//
// Created by Artem on 11/20/15.
//

#ifndef ALECTRYON_LINUX_CONSTANTS_H
#define ALECTRYON_LINUX_CONSTANTS_H

#define LINUX_USER_ENV "USER"
#define LINUX_HOME_DIR "/home/"

#endif //ALECTRYON_LINUX_CONSTANTS_H
